version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd server
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules
      - npm ci --production

artifacts:
  files:
    - package.json
    - package-lock.json
    - .ebextensions/**/*
    - .npmrc
    - Procfile
    - dist/**/*
    - node_modules/**/*
  base-directory: server
  discard-paths: no 